apiVersion: apps/v1
kind: Deployment
metadata:
  name: mstest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mstest
  template:
    metadata:
      labels:
        app: mstest
    spec:
      containers:
        - name: mstest
          image: xcoderx09/mstest-dev:latest
          ports:
            - containerPort: 8082
          env:
            - name: MONGO_HOST
              value: 192.168.0.109
          imagePullPolicy: Always